import axios from 'axios';

// Base API URL (reads from Vite env with localhost fallback)
const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000').replace(/\/$/, '');

// ============================================================================
// TypeScript Types - Matching Backend API Schemas
// ============================================================================

/**
 * Analysis result from an analyst agent
 */
export interface Analysis {
  id: string;
  category: string;
  finding: string;
  severity: number;  // 1-10 scale
  agent_type?: 'systems' | 'bizops' | null;  // Which agent generated this analysis
  finding_embedding?: number[] | null;
  blueprint_id?: string;
}

/**
 * Pro or Con item with point and description
 */
export interface ProCon {
  point: string;
  description: string;
}

/**
 * Architecture blueprint generated by the architect agent
 */
export interface Blueprint {
  id: string;
  name: string;
  description: string;
  pros: ProCon[];
  cons: ProCon[];
  analyses: Analysis[];
  mermaid_diagram?: string;  // LLM-generated Mermaid diagram syntax
  project_id?: string;
}

/**
 * Project metadata
 */
export interface Project {
  id: string;
  user_prompt: string;
  status: 'pending' | 'processing' | 'completed' | 'error';
  created_at: string;
  updated_at?: string;
}

/**
 * Complete project response including blueprints
 */
export interface ProjectResponse {
  project: Project;
  blueprints: Blueprint[];
}

/**
 * Response from starting a new project
 */
export interface StartProjectResponse {
  project_id: string;  // Backend returns 'project_id', not 'id'
  status: string;
  message: string;
}

/**
 * Search request payload
 */
export interface SearchRequest {
  query: string;
}

/**
 * Search response - array of analyses
 */
export type SearchResponse = Analysis[];

/**
 * Project list item
 */
export interface ProjectListItem {
  id: string;
  user_prompt: string;
  status: 'pending' | 'processing' | 'completed' | 'error';
  created_at: string;
  updated_at?: string;
}

/**
 * Projects list response
 */
export interface ProjectsListResponse {
  projects: ProjectListItem[];
  skip: number;
  limit: number;
  count: number;
}

// ============================================================================
// API Functions
// ============================================================================

/**
 * Get API root information
 * 
 * @returns Promise with welcome message and API info
 */
export async function getRoot(): Promise<{ message: string; version: string }> {
  try {
    const response = await axios.get(`${API_BASE_URL}/`);
    return response.data;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      throw new Error(
        `Failed to fetch root: ${error.response?.data?.detail || error.message}`
      );
    }
    throw error;
  }
}

/**
 * Check backend health status
 * 
 * @returns Promise with health status
 */
export async function checkHealth(): Promise<{ status: string }> {
  try {
    const response = await axios.get(`${API_BASE_URL}/health`);
    return response.data;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      throw new Error(
        `Health check failed: ${error.response?.data?.detail || error.message}`
      );
    }
    throw error;
  }
}

/**
 * List all projects with pagination
 * 
 * @param skip - Number of projects to skip (for pagination)
 * @param limit - Maximum number of projects to return
 * @param status - Optional status filter
 * @returns Promise with list of projects
 * 
 * @example
 * ```typescript
 * const history = await listProjects(0, 20);
 * console.log(history.projects); // Array of projects
 * 
 * // Filter by status
 * const completed = await listProjects(0, 20, 'completed');
 * ```
 */
export async function listProjects(
  skip: number = 0,
  limit: number = 20,
  status?: 'pending' | 'processing' | 'completed' | 'error'
): Promise<ProjectsListResponse> {
  try {
    const params: Record<string, any> = { skip, limit };
    if (status) {
      params.status = status;
    }

    const response = await axios.get<ProjectsListResponse>(
      `${API_BASE_URL}/projects`,
      { params }
    );
    return response.data;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      throw new Error(
        `Failed to fetch projects list: ${error.response?.data?.detail || error.message}`
      );
    }
    throw error;
  }
}

/**
 * Start a new project by sending a prompt to the backend
 * 
 * @param prompt - The architect agent's prompt (required)
 * @returns Promise with project data
 * 
 * @example
 * ```typescript
 * const result = await startProject("Build a real-time chat app");
 * console.log(result.project_id); // "550e8400-e29b-41d4-a716-446655440000"
 * ```
 */
export async function startProject(
  prompt: string
): Promise<StartProjectResponse> {
  try {
    const response = await axios.post<StartProjectResponse>(
      `${API_BASE_URL}/projects`,
      { user_prompt: prompt },
      {
        headers: {
          'Content-Type': 'application/json',
        },
      }
    );
    return response.data;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      throw new Error(
        `Failed to start project: ${error.response?.data?.detail || error.message}`
      );
    }
    throw error;
  }
}

/**
 * Get complete project results including all blueprints and analyses
 * 
 * @param projectId - The unique project identifier
 * @param useMockData - If true, fetches from mock-data.json instead of API
 * @returns Promise with complete project data
 * 
 * @example
 * ```typescript
 * const project = await getProjectResults("550e8400-e29b-41d4-a716-446655440000");
 * console.log(project.blueprints.length); // Number of blueprints
 * ```
 */
export async function getProjectResults(
  projectId: string,
  useMockData: boolean = false
): Promise<ProjectResponse> {
  try {
    if (useMockData) {
      // Fetch from mock data for UI development
      const response = await axios.get<ProjectResponse>('/mock-data.json');
      return response.data;
    }

    // Fetch from actual API
    const response = await axios.get<ProjectResponse>(
      `${API_BASE_URL}/projects/${projectId}`
    );
    return response.data;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      throw new Error(
        `Failed to fetch project results: ${error.response?.data?.detail || error.message}`
      );
    }
    throw error;
  }
}

/**
 * Get project status (useful for polling)
 * 
 * @param projectId - The unique project identifier
 * @returns Promise with project status information
 * 
 * @example
 * ```typescript
 * const statusInfo = await getProjectStatus("550e8400-e29b-41d4-a716-446655440000");
 * console.log(statusInfo.status); // "processing"
 * ```
 */
export async function getProjectStatus(projectId: string): Promise<{
  project_id: string;
  status: string;
  created_at: string;
  user_prompt: string;
}> {
  try {
    const response = await axios.get(
      `${API_BASE_URL}/projects/${projectId}/status`
    );
    return response.data;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      throw new Error(
        `Failed to fetch project status: ${error.response?.data?.detail || error.message}`
      );
    }
    throw error;
  }
}

/**
 * Search project analyses using hybrid keyword and semantic search
 * 
 * @param projectId - The unique project identifier
 * @param query - Search query string
 * @returns Promise with array of matching analyses
 * 
 * @example
 * ```typescript
 * const results = await searchProject("550e8400-e29b-41d4-a716-446655440000", "security");
 * console.log(results.length); // Number of matching analyses
 * results.forEach(analysis => {
 *   console.log(`${analysis.category}: ${analysis.finding}`);
 * });
 * ```
 */
export async function searchProject(
  projectId: string,
  query: string
): Promise<SearchResponse> {
  try {
    const response = await axios.post<SearchResponse>(
      `${API_BASE_URL}/projects/${projectId}/search`,
      { query },
      {
        headers: {
          'Content-Type': 'application/json',
        },
      }
    );
    return response.data;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      throw new Error(
        `Search failed: ${error.response?.data?.detail || error.message}`
      );
    }
    throw error;
  }
}

/**
 * Helper function to poll project status until completion
 * 
 * @param projectId - The unique project identifier
 * @param onStatusUpdate - Callback function called on each status update
 * @param interval - Polling interval in milliseconds (default: 3000)
 * @param maxAttempts - Maximum number of polling attempts (default: 100)
 * @returns Promise that resolves when project is completed or fails
 * 
 * @example
 * ```typescript
 * await pollProjectStatus(
 *   projectId,
 *   (status) => console.log(`Status: ${status}`),
 *   3000,
 *   100
 * );
 * ```
 */
export async function pollProjectStatus(
  projectId: string,
  onStatusUpdate: (status: string) => void,
  interval: number = 3000,
  maxAttempts: number = 100
): Promise<void> {
  let attempts = 0;

  return new Promise((resolve, reject) => {
    const pollInterval = setInterval(async () => {
      attempts++;

      if (attempts > maxAttempts) {
        clearInterval(pollInterval);
        reject(new Error('Polling timeout: Maximum attempts reached'));
        return;
      }

      try {
        const statusData = await getProjectStatus(projectId);
        onStatusUpdate(statusData.status);

        if (statusData.status === 'completed') {
          clearInterval(pollInterval);
          resolve();
        } else if (statusData.status === 'error') {
          clearInterval(pollInterval);
          reject(new Error('Project processing failed'));
        }
      } catch (error) {
        clearInterval(pollInterval);
        reject(error);
      }
    }, interval);
  });
}

/**
 * Delete a project and all its related data
 * 
 * @param projectId - Project UUID to delete
 * @returns Success message
 * @throws Error if deletion fails
 * 
 * @example
 * ```typescript
 * await deleteProject('550e8400-e29b-41d4-a716-446655440000');
 * ```
 */
export async function deleteProject(projectId: string): Promise<{ message: string; project_id: string }> {
  try {
    const response = await axios.delete(`${API_BASE_URL}/projects/${projectId}`);
    return response.data;
  } catch (error) {
    if (axios.isAxiosError(error)) {
      if (error.response?.status === 404) {
        throw new Error('Project not found');
      }
      throw new Error(
        `Failed to delete project: ${error.response?.data?.detail || error.message}`
      );
    }
    throw error;
  }
}

// ============================================================================
// Export all functions as a default object (alternative import style)
// ============================================================================

const api = {
  getRoot,
  checkHealth,
  listProjects,
  startProject,
  getProjectResults,
  getProjectStatus,
  searchProject,
  pollProjectStatus,
  deleteProject,
};

export default api;
